apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "benthos.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "benthos.labels" . | nindent 4 }}
data:
  benthos.yaml: |
  {{- if .Values.http.enabled }}
    http:
      enabled: true
      {{- if .Values.http.address }}
      address: {{ .Values.http.address | default "0.0.0.0:4195" }}
      {{- end -}}
      {{ if .Values.http.readTimeout }}
      read_timeout: {{ .Values.http.readTimeout | default "5s" }}
      {{- end -}}
      {{ if .Values.http.rootPath }}
      root_path: {{ .Values.http.rootPath | default "/benthos" }}
      {{- end -}}
      {{ if .Values.http.debugEndpoints }}
      debug_endpoints: {{ .Values.http.debugEndpoints | default false }}
      {{- end -}}
      {{ if .Values.http.cors.enabled }}
      cors:
        enabled: true
        {{- if .Values.http.cors.allowedOrigins }}
        allowed_origins: {{- range .Values.http.cors.allowedOrigins }}
          - {{ . }}
          {{- end }}
        {{- end }}
      {{- end -}}
      {{ if and .Values.http.tls.enabled .Values.http.tls.secretName }}
      cert_file: "/tls/tls.crt"
      key_file: "/tls/tls.key"
      {{- end -}}
    {{- if and .Values.config (ne .Values.streams.enable true) }}
    {{- tpl .Values.config . | nindent 4 }}
    {{- else }}
    input:
      label: "no_config_in"
      generate:
        mapping: root = "This Benthos instance is unconfigured!"
        interval: 1m
    output:
      label: "no_config_out"
      stdout:
        codec: lines
    {{- end -}}
  {{- end -}}
