{{- if .Values.http.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "benthos.fullname" . }}
  labels:
    {{- include "benthos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "benthos.selectorLabels" . | nindent 4 }}
{{- end -}}